### ISSUE TITLE
Enhancement: How to flag points that do or do not have photos?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARandFirstResponderSurvey#25]
@IsmaelInRedlands and I discussed a possible way to do this, will come back to it later.

**Comment by IsmaelInRedlands** [comment]
To do this, an extra hidden question could be added to the survey. The calculation column in that new question would look like this: 

string-length(${photo_question})

If the photo_question is empty, the question will be calculated with a 0, otherwise the value would be larger.  Having that in place will allow any ArcGIS Client (web map, web appbuilder, dashboard...) to easily filter out points without attachments.

**Comment by pjdohertygis** [comment]
Resolved - the Attachment Viewer allows to show points with only photos.
