### ISSUE TITLE
Enhancement: Adding Date/Time & Coordinates as Water Marks on the Photos

### ISSUE THREAD

**Issue by eshreveazdema** [pjdohertygis/SARandFirstResponderSurvey#27]
I am thinking it would be beneficial to add Date/Time, as well as Coordinates Watermarks to the Photos within Survey123.

**Comment by pjdohertygis** [comment]
See this post for documentation https://community.esri.com/groups/survey123/blog/2019/08/08/survey123-tricks-of-the-trade-photo-watermarks

**Comment by adf102** [comment]
I managed to get the watermarks to display the data correctly but I cannot manipulate the text in any way. I would like to increase the size and add a halo around the text to help it stand out a bit, but I have been having troubles with doing this. I had to add a new field for the watermark to take the geopoint data instead of the receiver data,. Below is a cut out of my progress. Any ideas in why I can't add a halo or text outline @tedrick? 

![Annotation 2019-12-05 163300](https://user-images.githubusercontent.com/55416740/70279868-ee52aa80-177c-11ea-8462-15c172bb64f3.png)

**Comment by tedrick** [comment]
@adf102 - append the desired properties to the watermark with & (similar to URL parameters).  As an example:
`bottomLeftWatermark="Bottom Left @[datetime:ddd MMMM dd yyyy  h:mm:ss]&size=20&color=grey&outlineColor=white"`

**Comment by adf102** [comment]
Thanks @tedrick , I got the date part working with that string working. Do you happen to know if S123 allows custom properties on user input watermarks? I'm trying to get the Lat/Long of the geopoint to show up as a watermark as well and I got it that it will at least display but every combination I tried with the other properties were disregarded and when I try to add the quotes (like the in the date/time) nothing shows up. This is my string:

topRightWatermark=${latlong}&size=20&color=grey&outlineColor=white

**Comment by tedrick** [comment]
@adf102 - it would be best to construct the string in a calculate question and then use that in the watermark.  See the 'Adding previously entered data from your form' section of https://community.esri.com/groups/survey123/blog/2019/08/08/survey123-tricks-of-the-trade-photo-watermarks

**Comment by adf102** [comment]
Alright I managed to get the watermarks the way that I wanted them showing date and time and pulling data from the geopoint. Here is the result:
![image](https://user-images.githubusercontent.com/55416740/71830961-82aa7880-306d-11ea-9551-0d0450e3b855.png)

Here's how:
1. Open Survey 123 Connect and open your survey, then open the XLSX editor
2. Create a new hidden row and call it watermark
3. Go to the calculation column of your new row and type in the following: *concat("Lat: ", ${latitude}, "\n ", "Long: ", ${longitude}, "&size=20&color=grey&outlineColor=white")*
4. Go to your photo attachments and find the ESRI Parameters column
5. Type in the following: *bottomLeftWatermark="@[datetime:ddd MMMM dd yyyy h:mm:ss]&size=20&color=grey&outlineColor=white" topRightWatermark=${watermark}*
6. Copy that string into the other photo attachments as well

**Comment by jdokemaps** [comment]
I included watermarks in the template. We wanted to use USNG instead of Lat Long (as noted above), so this is the calculation that I used in the esri parameters field for each of the image fields:
bottomLeftWatermark="@[datetime:ddd MMMM dd yyyy h:mm:ss]&size=20&color=grey&outlineColor=white" topRightWatermark="@[usng]&size=20&color=grey&outlineColor=white"
